### ISSUE TITLE
Queue ordering fails on multi push

### ISSUE THREAD

**Issue by arunraj88** [MishaConway/ruby-redis-unique-queue#1]
On doing a series of push_multi, queue order is not maintained. Check the given code to replicate the issue. Pardon my english.

`queue.push_multi (0..5000).to_a`
`queue.push_multi (5000..10000).to_a`
`queue.push_multi (10000..15000).to_a`

PFA screenshot of queue order
<img width="427" alt="screen shot 2017-05-17 at 6 12 02 pm" src="https://cloud.githubusercontent.com/assets/3961407/26154267/6d0279c6-3b2c-11e7-866b-c5c07ae682da.png">

**Comment by MishaConway** [comment]
@arunraj88 sorry I missed this. I'll be taking a look at this this week.

**Comment by MishaConway** [comment]
@arunraj88 Pushed out a fix for this and cut a new gem version. Let me know if you still have problems.
